import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { fetchProjectData } from './core/github-fetcher.js';
import { getAdapter, getGlobalInstructions } from './core/adapter-registry.js';
import { generateContent } from './core/ai-generator.js';
import { createPR, type FileChange } from './core/github-publisher.js';

const PORTFOLIO_OWNER = 'Git-Mere';
const PORTFOLIO_REPO = 'Git-Mere.github.io';

interface BatchConfig {
  featured: string[];  // GitHub repo URLs or owner/repo strings
  other: string[];
}

function parseGithubUrl(raw: string): { owner: string; repo: string } {
  // Accept https://github.com/owner/repo or owner/repo
  const m = raw.match(/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?\/?$/) ??
            raw.match(/^([^/]+)\/([^/]+?)(?:\.git)?$/);
  if (!m?.[1] || !m[2]) throw new Error(`Cannot parse GitHub repo URL: ${raw}`);
  return { owner: m[1], repo: m[2] };
}

// buildPortfolioMarkdown을 src/cli.ts에서 그대로 복사 (내용 동일하게 유지)
function buildPortfolioMarkdown(opts: {
  aiFields: Record<string, unknown>;
  owner: string;
  repo: string;
  homepage: string | null;
  isFeatured: boolean;
}): string {
  const { aiFields, owner, repo, homepage, isFeatured } = opts;
  const tech = (aiFields['tech'] as string[]).map((t) => `  - ${t}`).join('\n');
  const today = new Date().toISOString().split('T')[0];
  const githubUrl = `https://github.com/${owner}/${repo}`;

  if (isFeatured) {
    const lines = [
      '---',
      `date: ${today}`,
      `title: ${aiFields['title']}`,
      'cover: ./cover.png',
      `github: ${githubUrl}`,
      ...(homepage ? [`external: ${homepage}`] : []),
      'tech:',
      tech,
      '---',
    ];
    return `${lines.join('\n')}\n\n${aiFields['description']}\n`;
  } else {
    const lines = [
      '---',
      `date: ${today}`,
      `title: ${aiFields['title']}`,
      `github: ${githubUrl}`,
      ...(homepage ? [`external: ${homepage}`] : []),
      'tech:',
      tech,
      "company: ''",
      'showInProjects: true',
      '---',
    ];
    return `${lines.join('\n')}\n\n${aiFields['description']}\n`;
  }
}

async function main(): Promise<void> {
  const configPath = process.argv[2];
  if (!configPath) {
    process.stderr.write('Usage: pnpm batch-portfolio <config.json>\n');
    process.exit(1);
  }

  const token = process.env['GITHUB_TOKEN'];
  if (!token) {
    process.stderr.write('Error: GITHUB_TOKEN env var is required\n');
    process.exit(1);
  }

  const config = JSON.parse(readFileSync(configPath, 'utf8')) as BatchConfig;
  const allProjects = [
    ...config.featured.map(url => ({ url, isFeatured: true })),
    ...config.other.map(url => ({ url, isFeatured: false })),
  ];

  const [loaded, globalInstructions] = await Promise.all([
    getAdapter('github-pages-portfolio'),
    getGlobalInstructions(),
  ]);
  if (!loaded) throw new Error('adapter not found: github-pages-portfolio');

  const files: FileChange[] = [];

  for (const { url, isFeatured } of allProjects) {
    const { owner, repo } = parseGithubUrl(url);
    process.stderr.write(`Generating ${repo} (${isFeatured ? 'featured' : 'other'})...\n`);
    try {
      const data = await fetchProjectData({ owner, repo, token, userInput: {} });
      const typeInstruction = isFeatured ? 'Output type: featured' : 'Output type: other';
      const result = await generateContent({
        promptBase: loaded.promptBase,
        schema: loaded.schema,
        globalInstructions,
        adapterInstructions: `${loaded.instructions}\n\n${typeInstruction}`,
        data,
      });
      const stripped = result.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim();
      const aiFields = JSON.parse(stripped) as Record<string, unknown>;
      const markdown = buildPortfolioMarkdown({ aiFields, owner, repo, homepage: data.repo.homepage, isFeatured });
      const filePath = isFeatured
        ? `content/featured/${repo}/index.md`
        : `content/projects/${repo}.md`;
      files.push({ path: filePath, content: markdown });
      process.stderr.write(`  done: ${filePath}\n`);
    } catch (err) {
      process.stderr.write(`  FAILED: ${err instanceof Error ? err.message : String(err)}\n`);
    }
  }

  if (files.length === 0) {
    process.stderr.write('No files generated.\n');
    process.exit(1);
  }

  const today = new Date().toISOString().split('T')[0];
  const branch = `post-connector/batch-${today}`;
  process.stderr.write(`\nCreating PR with ${files.length} files on branch ${branch}...\n`);

  const prUrl = await createPR({
    token,
    owner: PORTFOLIO_OWNER,
    repo: PORTFOLIO_REPO,
    branch,
    baseBranch: 'main',
    title: `Add portfolio projects (${today})`,
    body: `Generated by Post Connector\n\n${files.map(f => `- \`${f.path}\``).join('\n')}`,
    files,
  });

  process.stdout.write(`PR created: ${prUrl}\n`);
}

main().catch((err: unknown) => {
  process.stderr.write(`Error: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
